id: P001738
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 2021-12-17 10:17:40.118129
source_metadata:
  id: bdr:W1KG9296
  title: ཨ་ཁུ་ཆིང་ནོཏེས
  author: ''
  volumes:
    edb1e16be7f84108b7d6b7730988725f:
      image_group_id: I1KG9382
      title: ''
      volume_number: 1
      total_pages: 190
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
