id: I20E03650
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T06:15:33+00:00'
last_modified: '2022-06-07T14:15:09.362697+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG9296
  title: ཨ་ཁུ་ཆིང་ནོཏེས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessRestrictedByTbrc
  restrictedInChina: false
  base:
    E83E:
      image_group_id: I1KG9382
      title: ''
      total_pages: 190
      order: 1
      base_file: E83E.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
